CONFIG_NAME: 'MirrorGAN'
DATASET_NAME: 'birds'
DATA_DIR: '../data/birds'
GPU_ID: 0
WORKERS: 1

B_VALIDATION: True  # True  # False
TREE:
    BRANCH_NUM: 3

TRAIN:
    FLAG: False
    NET_G: 'data/output/bird/Model/netG.pth'   # path to the trained model
    B_NET_D: False
    BATCH_SIZE: 12
    NET_E: 'data/STEM/text_encoder.pth'
GAN:
    DF_DIM: 64
    GF_DIM: 32
    Z_DIM: 100
    R_NUM: 2

TEXT:
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 10
    WORDS_NUM: 25

######
CAP:
    embed_size: 256
    hidden_size: 256
    num_layers: 1
    learning_rate: 0.001
    caption_cnn_path: 'data/STREAM/cnn_encoder.ckpt'
    caption_rnn_path: 'data/STREAM/rnn_decoder.ckpt'
